INSERT INTO GENRES(name) VALUES ('Комедия');
INSERT INTO GENRES(name) VALUES ('Драма');
INSERT INTO GENRES(name) VALUES ('Мультфильм');
INSERT INTO GENRES(name) VALUES ('Триллер');
INSERT INTO GENRES(name) VALUES ('Документальный');
INSERT INTO GENRES(name) VALUES ('Боевик');

INSERT INTO MPA(name) VALUES('G');
INSERT INTO MPA(name) VALUES('PG');
INSERT INTO MPA(name) VALUES('PG-13');
INSERT INTO MPA(name) VALUES('R');
INSERT INTO MPA(name) VALUES('NC-17');